name: Health check

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-hidden-dust-8085.fly.dev/
